---
- block:
  - name: cask versions tap
    homebrew_tap:
      name: homebrew/cask-versions
  - name: safari technology preview
    homebrew_cask:
      name: safari-technology-preview
- name: Firefox Developer Edition
  homebrew_cask:
    name: firefox-developer-edition
- name: Google Chrome Canary
  homebrew_cask:
    name: google-chrome-canary
