---
# Firefox Stable
- name: Add Firefox Stable.
  become: yes
  apt:
    name: firefox
    update_cache: yes
    cache_valid_time: 3600

# Firefox Developer Edition
- name: Add Ubuntu Make snap
  snap:
    name: ubuntu-make
    classic: yes

- name: Check if Firefox Developer Edition has been installed.
  stat:
    path: ~/.local/share/umake/web/firefox-dev
  register: firefox_dev

# TODO: This is not working 100%. Needs to be manually ran.
# - name: Add Firefox Developer Edition.
#   command: umake web firefox-dev
#   args:
#     creates: ~/.local/share/umake/bin/firefox-develop
#   when: firefox_dev.stat.exists == False

# Google Chrome Stable
- name: Does the Google apt file exist?
  command: test -f {{debian.chrome_stable.apt_file}}
  register: google_apt_exists
  ignore_errors: True

- name: Add Google Chrome key
  become: yes
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  when: google_apt_exists.rc == 1

- name: Add Google Chrome repo
  become: yes
  copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest={{debian.chrome_stable.apt_file}} owner=root group=root mode=644
  when: google_apt_exists.rc == 1

- name: Update apt cache
  become: yes
  apt: update_cache=yes
  when: google_apt_exists.rc == 1

- name: Install Google Chrome Stable.
  become: yes
  apt: pkg=google-chrome-stable state=present

# Google Chrome Beta
- name: Install Google Chrome Beta.
  become: yes
  apt: pkg=google-chrome-beta state=present
