---
# Setup
- name: Add Ubuntu Make repository.
  apt_repository:
    repo: ppa:ubuntu-desktop/ubuntu-make

- name: Add Ubuntu Make.
  apt:
    name: ubuntu-make

# Browsers
- name: Check if Firefox Developer Edition has been installed.
  stat:
    path: ~/.local/share/umake/web/firefox-dev
  register: firefox_dev

- name: Add Firefox Developer Edition.
  command: umake web firefox-dev
  args:
    creates: ~/.local/share/umake/bin/firefox-develop
  when: firefox_dev.stat.exists == False

- name: Add Google Chrome.
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
