---
- hosts: local
  connection: local

  vars_files:
    - default.config.yml

  roles:
    - role: geerlingguy.homebrew
    - role: geerlingguy.mas

  tasks:
    - name: 1password
      homebrew_cask:
        name: 1password
    - name: Homebrew Cask upgrade.
      homebrew_tap:
        name: buo/cask-upgrade
    - block:
      - name: rcm tap
        homebrew_tap:
          name: thoughtbot/formulae
      - name: rcm install
        homebrew:
          name: rcm
    - name: zsh
      homebrew:
        name: zsh
    - name: direnv
      homebrew:
        name: direnv
    - name: yarn
      homebrew:
        name: yarn
        install_options: without-node
    - name: tmux
      homebrew:
        name: tmux
    - name: htop
      homebrew:
        name: htop
    - name: vim
      homebrew:
        name: vim
    - name: dash
      homebrew_cask:
        name: dash
    - name: ag
      homebrew:
        name: ag
    - block:
      - name: ruby-build
        homebrew:
          name: ruby-build
      - name: rbenv
        homebrew:
          name: rbenv
    - name: imageoptim
      homebrew_cask:
        name: imageoptim
    - name: git
      homebrew:
        name: git
    - name: git-lfs
      homebrew:
        name: git-lfs
    - block:
      - name: cask versions tap
        homebrew_tap:
          name: homebrew/cask-versions
      - name: safari technology preview
        homebrew_cask:
          name: safari-technology-preview
    - name: Firefox Developer Edition
      homebrew_cask:
        name: firefox-developer-edition
    - name: wget
      homebrew:
        name: wget
    - name: Google Chrome Canary
      homebrew_cask:
        name: google-chrome-canary
    - name: Docker
      homebrew_cask:
        name: docker
    - name: pyenv
      homebrew:
        name: pyenv
    - name: AWS CLI
      pip:
        name: awscli
        state: latest
    - name: AWS SAM CLI
      pip:
        name: aws-sam-cli
        state: latest
    - name: Insomnia REST client
      homebrew_cask:
        name: insomnia
        state: present
    - name: Remote Desktop Client
      homebrew_cask:
        name: microsoft-remote-desktop-beta
        state: present
    - name: MySQL Client
      homebrew_cask:
        name: sequel-pro-nightly
        state: present
    - name: bat
      homebrew: name=bat state=present
