---
- hosts: local
  connection: local

  vars_files:
    - "vars/common.yml"
    - [ "vars/{{ ansible_facts['os_family'] }}.yml", "vars/os_defaults.yml" ]

  roles:
    - role: geerlingguy.homebrew
      when: ansible_os_family == 'Darwin'
    - role: geerlingguy.mas
      when: ansible_os_family == 'Darwin'
    - role: browsers

  tasks:
    - name: 1password
      when: ansible_os_family == 'Darwin'
      homebrew_cask:
        name: 1password
    - name: Homebrew Cask upgrade.
      when: ansible_os_family == 'Darwin'
      homebrew_tap:
        name: buo/cask-upgrade
    - name: rcm
      when: ansible_os_family == 'Debian'
      include_role:
        name: karlmdavis.rcm-dotfiles
      vars:
        rcm_user: dylan
        rcm_repos:
          - repo: 'https://github.com/dylanpinn/dotfiles'
            # TODO: Get this working for MacOS.
            dest: '/home/dylan/.dotfiles'
    - name: zsh
      homebrew:
        name: zsh
    - name: direnv
      homebrew:
        name: direnv
    - name: yarn
      block:
      - name: yarn debian
        when: ansible_os_family == 'Debian'
        homebrew:
          name: yarn
      - name: yarn macos
        when: ansible_os_family == 'Darwin'
        homebrew:
          name: yarn
          install_options: without-node
    - name: tmux
      homebrew:
        name: tmux
    - name: htop
      homebrew:
        name: htop
    - name: vim
      homebrew:
        name: vim
    - name: dash
      when: ansible_os_family == 'Darwin'
      homebrew_cask:
        name: dash
    - name: ag
      homebrew:
        name: ag
    - block:
      - name: ruby-build
        homebrew:
          name: ruby-build
      - name: rbenv
        homebrew:
          name: rbenv
    - name: imageoptim
      when: ansible_os_family == 'Darwin'
      homebrew_cask:
        name: imageoptim
    - name: git
      homebrew:
        name: git
    - name: git-lfs
      homebrew:
        name: git-lfs
    - name: wget
      homebrew:
        name: wget
    - name: Docker
      when: ansible_os_family == 'Darwin'
      homebrew_cask:
        name: docker
    - name: pyenv
      homebrew:
        name: pyenv
    - name: AWS CLI
      pip:
        name: awscli
        state: latest
    - name: AWS SAM CLI
      pip:
        name: aws-sam-cli
        state: latest
    - name: Insomnia REST client
      when: ansible_os_family == 'Darwin'
      homebrew_cask:
        name: insomnia
        state: present
    - name: Remote Desktop Client
      when: ansible_os_family == 'Darwin'
      homebrew_cask:
        name: microsoft-remote-desktop-beta
        state: present
    - name: MySQL Client
      when: ansible_os_family == 'Darwin'
      homebrew_cask:
        name: sequel-pro-nightly
        state: present
    - name: bat
      homebrew: name=bat state=present
    - name: ansible
      pip:
        name: ansible
        state: latest
