---
- hosts: local
  connection: local
  tasks:
    - name: 1password
      homebrew_cask:
        name: 1password
    - block:
      - name: rcm tap
        homebrew_tap:
          name: thoughtbot/formulae
      - name: rcm install
        homebrew:
          name: rcm
    - name: zsh
      homebrew:
        name: zsh
    - name: direnv
      homebrew:
        name: direnv
    - name: yarn
      homebrew:
        name: yarn
        install_options: without-node
    - name: tmux
      homebrew:
        name: tmux
    - name: htop
      homebrew:
        name: htop
    - name: vim
      homebrew:
        name: vim
    - name: dash
      homebrew_cask:
        name: dash
    - name: ag
      homebrew:
        name: ag
    - block:
      - name: ruby-build
        homebrew:
          name: ruby-build
      - name: rbenv
        homebrew:
          name: rbenv
    - name: imageoptim
      homebrew_cask:
        name: imageoptim
    - name: git
      homebrew:
        name: git
    - name: git-lfs
      homebrew:
        name: git-lfs
    - block:
      - name: cask versions tap
        homebrew_tap:
          name: homebrew/cask-versions
      - name: safari technology preview
        homebrew_cask:
          name: safari-technology-preview
